### ISSUE TITLE
Using http.Request.Context instead of the Background context

### ISSUE THREAD

**Issue by sAbakumoff** [graphql-go/handler#20]
In https://github.com/graphql-go/handler/blob/master/handler.go#L148
how about modifying it to
```golang
h.ContextHandler(r.Context(), w, r)
```
The idea is in that the middleware can add something in the request's context and pass it further to the handler that passes it further to the GraphQL query. The example is a cookie value.

**Comment by maxbeatty** [comment]
👍 would like to see this #12 #14 #17 all looking for the same 😁

**Comment by yasarix** [comment]
I'd like to see this too. I'm trying to use graphql-go on App Engine. I need to get appengine context.

**Comment by yasarix** [comment]
I wanted to give an update on this, so other people who wants to use handler in app engine doesn't have to waste their time. This is the solution:
There is a `ContextHandler()` method in handler.Handler struct. When you setup the `http.Handle()`, you can call a custom function to pass the app engine's context like this:

```
func init() {
...
...
	h := handler.New(&handler.Config{
		Schema: &Schema,
		Pretty: true,
	})

	http.Handle("/graphql", customHandler(h))
...
...
...
}

func customHandler(h *handler.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := appengine.NewContext(r)
		log.Debugf(ctx, "Request came: %v", r.Host)

		// Call context handler to serve HTTP
		h.ContextHandler(ctx, w, r)
	})
}
```

This worked for me. I hope this helps others.

**Comment by yookoala** [comment]
#24 is merged. I believe this issue has been resolved.

**Comment by chris-ramon** [comment]
thanks a lot for your awesome comments!, closing this one, addressed via: https://github.com/graphql-go/handler/pull/24
