### ISSUE TITLE
New tag with the formatting error changes?

### ISSUE THREAD

**Issue by tapocol** [graphql-go/handler#63]
The graphql library has been tagged with v0.7.7 with the formatting error changes: https://github.com/graphql-go/graphql/tree/v0.7.7

Will this repo be getting a tagged version soon that correlates to that tag on the graphql repo?

**Comment by chris-ramon** [comment]
Hi @tapocol! thanks for the friendly reminder :+1: , I've just released [graphql-go/handler v0.2.3](https://github.com/graphql-go/handler/releases/tag/v0.2.3) which targets latest [graphql-go/graphql v0.7.7](https://github.com/graphql-go/graphql/releases/tag/v0.7.7)

**Comment by tapocol** [comment]
It looks like there is a mixup. https://github.com/graphql-go/graphql/commits/v0.7.7 *does not* include a commit for "consolidates original error to allow custom format error". Yet, handler tag https://github.com/graphql-go/handler/commits/v0.2.3 *does* include a commit for "handler: consolidate FormatErrorFn"

It seems like these tags are incompatible. as `FormatErrorFn` in the `handler` package seems to just get `nil` for the `error` from the `graphql/gqlerrors` package.

**Comment by tapocol** [comment]
> It seems like these tags are incompatible. as `FormatErrorFn` in the `handler` package seems to just get `nil` for the `error` from the `graphql/gqlerrors` package.

Oh, this looks like it is `nil` because now instead of the context of `gqlerrors.FormattedError` in the argument, that argument is stripped to the result of `OriginalError()` call to the `FormattedError`. Which in the case of my testing `originalError` on `FormattedError` was not being set.
